// Code is generated by Telerik Add OpenAccess Service Wizard
// using WebApiRepositories.tt template

using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Telerik.OpenAccess;
using KendoModel;

namespace KendoWebApi
{
	public partial class ClienteRepository : OpenAccessBaseRepository<KendoModel.Cliente, KendoModel.KendoContext>
    {
	
    }

	public partial class GrupoClienteRepository : OpenAccessBaseRepository<KendoModel.GrupoCliente, KendoModel.KendoContext>
    {
	
    }

}
