#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KendoModel;


namespace KendoModel	
{
	public partial class GrupoCliente
	{
		private int _grupoId;
		public virtual int GrupoId 
		{ 
		    get
		    {
		        return this._grupoId;
		    }
		    set
		    {
		        this._grupoId = value;
		    }
		}
		
		private string _nombre;
		public virtual string Nombre 
		{ 
		    get
		    {
		        return this._nombre;
		    }
		    set
		    {
		        this._nombre = value;
		    }
		}
		
		private IList<Cliente> _clientes = new List<Cliente>();
		public virtual IList<Cliente> Clientes 
		{ 
		    get
		    {
		        return this._clientes;
		    }
		}
		
	}
}
